FROM node:latest

#keys
ARG discord-arg
ARG author-arg

ENV discord-arg=$discord-arg
ENV author-arg=$author-arg

# Create the bot's directory
RUN mkdir -p /usr/src/bot
WORKDIR /usr/src/bot

RUN git clone https://github.com/max-meme/bouncy-bot2
WORKDIR /usr/src/bot/bouncy-bot2

RUN touch creds.json
RUN touch settings.json

RUN echo '{{"discord_token": "TOKEN HERE","author": "AUTHOR HERE"}}' > creds.json
RUN echo "{}" > settings.json

# Start the bot.
CMD ["node", "bot.js"]